---
- name: Create apache2 configuration
  template:
    src: vhost-configuration.js2
    dest: /etc/apache2/sites-available/{{ project_name }}-configuration.conf

- name: Enable apache2 vhosts
  file:
    src: /etc/apache2/sites-available/{{ project_name }}-configuration.conf
    dest: /etc/apache2/sites-enabled/{{ project_name }}-configuration.conf
    state: link
  notify: restart apache

- name: Create prod database
  mysql_db:
    name: "{{ item }}"
    state: present
    collation: utf8_general_ci
  with_items: project_databases

- name: create static resource dir
  file: path=/var/www/content-block-bundle/features/fixtures/project/web/bundles
        state=directory
        mode=0775

- name: symlink public folder
  file: dest=/var/www/content-block-bundle/features/fixtures/project/web/bundles/fsicontentblock
        src=../../../../../Resources/public
        state=link
        force=yes
