fsi_admin:
    path: /
    defaults:
        _controller: FSiAdminBundle:Admin:index

fsi_admin_crud_list:
    path: /{element}/list
    defaults:
        _controller: FSiAdminBundle:CRUD:list

fsi_admin_crud_create:
    path: /{element}/create
    defaults:
        _controller: FSiAdminBundle:CRUD:create

fsi_admin_crud_edit:
    path: /{element}/edit/{id}
    defaults:
        _controller: FSiAdminBundle:CRUD:edit

fsi_admin_crud_delete:
    path: /{element}/delete
    defaults:
        _controller: FSiAdminBundle:CRUD:delete
    requirements:
        _method:  DELETE

fsi_admin_resource:
    path: /resource/{element}
    defaults:
        _controller: FSiAdminBundle:Resource:resource