fsi_admin:
    path: /
    defaults:
        _controller: admin.controller.admin:indexAction

fsi_admin_crud_list:
    path: /{element}/list
    defaults:
        _controller: admin.controller.crud:listAction

fsi_admin_crud_create:
    path: /{element}/create
    defaults:
        _controller: admin.controller.crud:createAction

fsi_admin_crud_edit:
    path: /{element}/edit/{id}
    defaults:
        _controller: admin.controller.crud:editAction

fsi_admin_crud_delete:
    path: /{element}/delete
    defaults:
        _controller: admin.controller.crud:deleteAction
    methods: [DELETE]

fsi_admin_resource:
    path: /resource/{element}
    defaults:
        _controller: admin.controller.resource:resourceAction