---
- name: Validate php version
  fail: msg="Unknown php version {{ php_version }}. Could be one of 5.3, 5.4, 5.5"
  when: php_version != 5.3 and php_version != 5.4 and php_version != 5.5

- name: Install required package
  apt: name=python-pycurl state=latest
  when: php_version == 5.4 or php_version == 5.5

- name: Add php repository
  apt_repository: repo='ppa:ondrej/php5-oldstable' state=present
  when: php_version == 5.4

- name: Add php repository
  apt_repository: repo='ppa:ondrej/php5' state=present
  when: php_version == 5.5

- name: Install PHP 
  apt: name=php5 state=latest

- name: Install PHP packages
  apt: name={{ item }} state=latest
  with_items:
    - php-apc
    - php5-cli
    - php5-gd
    - php5-mysql
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-sqlite

- name: Configure PHP for apache and CLI
  template: src=php_config.ini.j2 dest=/etc/php5/conf.d/php_config.ini
  when: php_version == 5.3

- name: Configure PHP for apache
  template: src=php_config.ini.j2 dest=/etc/php5/apache2/conf.d/php_config.ini
  when: php_version == 5.5 or php_version == 5.4

- name: Configure PHP for CLI
  template: src=php_config.ini.j2 dest=/etc/php5/cli/conf.d/php_config.ini
  when: php_version == 5.5 or php_version == 5.4
